package ucan.edu.academic.entities;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.Set;

@NoArgsConstructor
@Getter
@Setter
@Entity
@Table(name = "disciplina")
public class Disciplina {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer pkDisciplina;
    private String nomeDisciplina;

    @Column(unique=true)
    private String codigoDisciplina;

    private Integer creditos;
    private Integer cargaHoraria;
    private Integer semestre;


    @OneToMany(mappedBy = "disciplina")
    @JsonIgnore
    private Set<DisciplinaPreRequisito> preRequisitos;

    @OneToMany(mappedBy = "preRequisito")
    @JsonIgnore
    private Set<DisciplinaPreRequisito> disciplinasQuePreRequisitam;

    public Disciplina(String nomeDisciplina, String codigoDisciplina, Integer creditos, Integer cargaHoraria, Integer semestre) {
        this.nomeDisciplina = nomeDisciplina;
        this.codigoDisciplina = codigoDisciplina;
        this.creditos = creditos;
        this.cargaHoraria = cargaHoraria;
        this.semestre = semestre;
    }

    //Constructor, getter and setter generated by lombok
}